### PR TITLE
Added ability to toggle confirmed and interpreter

### LINKED ISSUE #42: Support Sanctuary changing confirmation
Sanctuary should be able to update any record to "Yes", "No" or "Interpreter". Currently, only changing from unconfirmed to "Yes" is allowed.

### LINKED ISSUE #43: Distinguish between no response and "No" response
Change the summary table and details page:

- Label the field "Response" rather than "Confirmed".
- If no response has been given yet, show "None".
- If the user responded "Yes", show "Confirmed".
- If the user responded "No", show "Declined".

### PR DESCRIPTION
**Pull request by Wiles**
Closes #42 

Closes #43 

Added button to toggle interpreter. Allowed un-confirming appointment. Added current interpreter status to UI.

Must be deployed after https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-api/pull/82

Before: 

before

Now:

no-no
yes-yes

### CODE REVIEW

**Review by iamstevedavis — APPROVED** [review]

**Comment by Wiles** [comment]
@KrisBraun Is the new wording okay?

**Comment by KrisBraun** [comment]
> @KrisBraun Is the new wording okay?

Is it possible to incorporate the wording changes in #43?

I'm fine with the current language if it will be replaced by the language from #43 in a future PR.

**Comment by Wiles** [comment]
@KrisBraun 

details
confirmed
none

**Comment by Wiles** [comment]
@KrisBraun I have also updated the appointments list to use the new text.

appointments

**Review by iamstevedavis — APPROVED** [review]

**Comment by KrisBraun** [comment]
@Wiles This is awesome! Looks great.

**Pull request merged**
